In [1]:
import numpy as np

In [2]:
x = np.array([2,4,5])
y = np.array([4,2,6])

In [3]:
y + x

array([ 6,  6, 11])

In [4]:
y -x 

array([ 2, -2,  1])

In [5]:
y /x

array([2. , 0.5, 1.2])

In [6]:
#dot product
y = np.array([2,4,5,6])
x = np.array([3,4,5,2])

np.dot(y,x)

59

In [8]:
#hadamard product
y = np.array([2,3,4])
x = np.array([8,2,1])
y * x

array([16,  6,  4])

# MATRIX MULTIPLICATION

In [9]:
matrix_a=[[2,4,5],
         [1,6,2]
         ]
matrix_b = [[1,6],
           [3,1],
            [1,2]
           ]

In [11]:
def matrix_mult(matrix_a, matrix_b):
    if len(matrix_a[0])!= len(matrix_b):
        raise ValueError("Incompatible matrix shapes")
        
    result = []
    
    for row in range(len(matrix_a)):
        newRow = []
        for col in range(len(matrix_b[0])):
            dot_product = sum(matrix_a[row][k] * matrix_b[k][col] for k in range(len(matrix_b)))
            newRow.append(dot_product)
        result.append(newRow)
        
    return result
        

In [12]:
res = matrix_mult(matrix_a, matrix_b)
res

[[19, 26], [21, 16]]

# MATRIX TRANSPOSE

In [13]:
matrix_a

[[2, 4, 5], [1, 6, 2]]

In [14]:
def transposeMatrix(m):
    tm = []
    for i in range(len(m[0])):
        newRow = []
        for j in range(len(m)):
            newRow.append(m[j][i])
        tm.append(newRow)
        
    return tm
    

In [22]:
transposeMatrix(matrix_a)

[[2, 4], [1, 6], [5, 2]]

In [37]:
#sparse matrices
m_a = [[0,2,0,0,0],
      [0,0,0,0,0],
       [0,1,0,0,0],
       [0,1,0,0,0],
       [0,0,0,0,0]
      ]
m_b = [[0,0,0,0,0],
      [0,0,0,0,0],
       [0,2,0,0,0],
       [0,1,0,2,0],
       [0,0,0,0,0]
      ]

In [38]:
def sparse_mm(matrix_a, matrix_b):
    if len(matrix_a[0]) != len(matrix_b):
        return [[]]
    
    s_a = get_useful_values(matrix_a)
    s_b = get_useful_values(matrix_b)
    
    matrix_c = [[0] * len(matrix_b[0]) for _ in range(len(matrix_a))]
    
    for i, k in s_a.keys():
        for j in range(len(matrix_b[0])):
            if (k,j) in s_b.keys():
                matrix_c[i][j] += s_a[(i,k)] * s_b[(k,j)]
    return matrix_c

def get_useful_values(matrix):
    res = {}
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            if matrix[i][j] != 0:
                res[(i,j)] = matrix[i][j]
                
    return res


In [39]:
res = sparse_mm(m_a, m_b)
res

[[0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0]]

In [40]:
a = [[0,2,0],
    [0,0,0]
    ]
b = [[0,1],
    [2,0],
     [1,0]
    ]
res = sparse_mm(a,b)
res

[[4, 0], [0, 0]]