In [2]:
import numpy as np
from lark.tools.nearley import nearley_grammar_parser

In [3]:
a = [x for x in range(1000)]

In [4]:
A = np.arange(1000, dtype=np.uint8)

In [5]:
B = np.arange(0,100, 2, dtype=np.uint8)
B

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98],
      dtype=uint8)

In [6]:
my_arr = [[1,2],[3,4],[5,6]]
np_arr = np.array(my_arr)
type(np_arr)

numpy.ndarray

In [102]:
np_arr[0]

array([1, 2])

In [8]:
np_arr[:,0]

array([1, 3, 5])

In [9]:
np_arr[:,0:]

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
np_arr[:,-1]

array([2, 4, 6])

In [101]:
N = 8

In [12]:
D = np.random.rand(N,N).astype(np.float32)
D

array([[0.07992746, 0.18368015, 0.5082169 , 0.7059762 , 0.39189538,
        0.86520416, 0.6943562 , 0.80783105, 0.9825673 , 0.6333944 ,
        0.85142905, 0.7025858 , 0.03552789, 0.31417525, 0.2933001 ,
        0.9005382 ],
       [0.06646489, 0.79579806, 0.10586091, 0.97745305, 0.3159692 ,
        0.6323592 , 0.4366026 , 0.86220247, 0.70908844, 0.5944074 ,
        0.909467  , 0.278099  , 0.7944445 , 0.5811656 , 0.7929477 ,
        0.67567396],
       [0.00444955, 0.75057834, 0.40447983, 0.7327343 , 0.24699447,
        0.8675703 , 0.28077504, 0.83556   , 0.1025776 , 0.95949554,
        0.914678  , 0.43762755, 0.22434163, 0.45786119, 0.18993518,
        0.08426195],
       [0.01020021, 0.8336913 , 0.5932557 , 0.0062347 , 0.83269095,
        0.5170118 , 0.39132255, 0.9881032 , 0.43651372, 0.02797143,
        0.55168647, 0.5890991 , 0.05800788, 0.01780056, 0.27538773,
        0.98733217],
       [0.1930565 , 0.3430797 , 0.55991757, 0.22710088, 0.2457886 ,
        0.4633769 , 0.68923384, 

In [116]:
E = np.zeros((N,N), dtype = np.float32)
E

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [14]:
I = np.eye(N,N).astype(dtype=np.float32)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [56]:
T = np.random.randn(N,N)
T

array([[-0.17730127,  0.08000693, -0.53241631,  1.24532529,  2.08812049,
        -0.05767292, -0.52111033, -0.27973741,  1.25813796, -0.07412547,
         0.874984  ,  0.47552317, -0.41631432,  0.25073755,  1.58997733,
         1.40794282],
       [-0.25447181, -1.0588868 ,  0.06386864, -0.46324028,  0.46604841,
         2.77137883,  0.56134906, -0.82992597,  0.35437129, -0.72340441,
        -0.23076733, -0.30817638,  0.26393379, -0.04158089, -1.44194982,
         0.63656305],
       [-0.67374657,  0.51989169, -0.07171487,  2.66536316,  0.58991759,
         0.73937969, -0.62842664, -0.79776966, -2.23438429,  0.54733547,
        -0.48967895,  0.80400697,  1.33858454, -1.29088484,  2.30286837,
         1.24096989],
       [-0.17478531, -1.68811684, -0.7144473 ,  1.0489537 ,  0.47473782,
        -0.19183979, -0.08144682,  0.93214843, -0.7444968 , -0.03707979,
        -0.70909224,  1.11558665,  1.83932858, -0.0561217 , -0.22507073,
         0.36861614],
       [ 0.44338511,  0.92125596,  0

In [76]:
T01 = np.random.rand(N,N)
T01

array([[7.90079932e-01, 3.88430707e-02, 2.89771575e-02, 2.67914893e-01,
        9.66494486e-01, 6.48049669e-01, 5.37547260e-01, 8.34489756e-01,
        4.39991091e-04, 5.13785245e-01, 6.84489855e-02, 5.00010856e-02,
        1.08938901e-01, 5.73934050e-01, 1.80028044e-01, 6.55862956e-01],
       [5.11493634e-01, 1.63273190e-01, 1.39288259e-01, 3.39145567e-01,
        5.90136144e-01, 7.39418383e-01, 8.68238235e-01, 9.34383852e-01,
        1.43465037e-01, 5.79916896e-01, 4.84181952e-01, 3.11320532e-01,
        5.79698528e-01, 4.53814883e-01, 8.90904285e-01, 1.84587956e-01],
       [8.77048727e-01, 8.92814007e-02, 4.73286140e-01, 9.75953189e-01,
        8.53200363e-01, 7.20867739e-01, 3.29754100e-01, 7.10186664e-01,
        3.24800693e-01, 7.59495924e-01, 8.16380999e-01, 1.51777161e-01,
        6.61238052e-01, 4.81927275e-03, 4.05987081e-01, 7.15242631e-01],
       [5.67424319e-01, 7.13087086e-01, 6.92356812e-01, 3.49415247e-01,
        2.20085778e-01, 1.33997181e-01, 8.16396163e-01, 8.945

In [77]:
l = [[2,3,4,5],
     [4,3,5,2],
     [1,2,3,4],
     [9,2,3,4]]


In [79]:
A = np.array(l)
A

array([[2, 3, 4, 5],
       [4, 3, 5, 2],
       [1, 2, 3, 4],
       [9, 2, 3, 4]])

In [80]:
A[:2,2:]


array([[4, 5],
       [5, 2]])

In [81]:
A[2:,1:3]

array([[2, 3],
       [2, 3]])

In [104]:
np.random.seed(42)

In [100]:
A = np.random.randn(N,N).astype(np.float32)

In [106]:
B = np.random.randn(N,N).astype(np.float32)

In [89]:
A

array([[ 0.49671414, -0.1382643 ,  0.64768857,  1.5230298 , -0.23415338,
        -0.23413695,  1.5792128 ,  0.7674347 , -0.46947438,  0.54256004,
        -0.46341768, -0.46572974,  0.24196227, -1.9132802 , -1.7249179 ,
        -0.5622875 ],
       [-1.0128311 ,  0.31424734, -0.9080241 , -1.4123037 ,  1.4656488 ,
        -0.2257763 ,  0.0675282 , -1.4247482 , -0.54438275,  0.11092259,
        -1.1509936 ,  0.37569803, -0.6006387 , -0.29169375, -0.6017066 ,
         1.8522782 ],
       [-0.01349723, -1.0577109 ,  0.82254493, -1.2208437 ,  0.2088636 ,
        -1.9596701 , -1.328186  ,  0.19686124,  0.73846656,  0.17136829,
        -0.11564828, -0.30110368, -1.478522  , -0.7198442 , -0.46063876,
         1.0571222 ],
       [ 0.3436183 , -1.7630402 ,  0.32408398, -0.38508227, -0.676922  ,
         0.6116763 ,  1.0309995 ,  0.93128014, -0.83921754, -0.3092124 ,
         0.33126342,  0.9755451 , -0.47917423, -0.18565898, -1.1063349 ,
        -1.1962066 ],
       [ 0.8125258 ,  1.35624   , -0

In [90]:
B

array([[ 1.2669111 , -0.70766944,  0.44381943,  0.77463406, -0.9269305 ,
        -0.05952536, -3.2412674 , -1.0243876 , -0.25256816, -1.2477832 ,
         1.6324114 , -1.4301413 , -0.4400445 ,  0.13074058,  1.4412733 ,
        -1.4358622 ],
       [ 1.1631638 ,  0.01023306, -0.9815087 ,  0.4621035 ,  0.1990597 ,
        -0.60021687,  0.06980208, -0.3853136 ,  0.11351734,  0.66213065,
         1.5860168 , -1.2378155 ,  2.1330333 , -1.9520878 , -0.15178509,
         0.5883172 ],
       [ 0.28099188, -0.6226995 , -0.20812225, -0.49300092, -0.58936477,
         0.8496021 ,  0.3570155 , -0.6929096 ,  0.89959985,  0.30729952,
         0.8128621 ,  0.62962884, -0.828995  , -0.560181  ,  0.7472936 ,
         0.6103703 ],
       [-0.02090159,  0.11732738,  1.2776649 , -0.5915714 ,  0.5470974 ,
        -0.20219265, -0.2176812 ,  1.0987768 ,  0.8254163 ,  0.81350964,
         1.3054788 ,  0.02100384,  0.68195295, -0.31026676,  0.32416636,
        -0.13014306],
       [ 0.09699596,  0.595157  , -0

In [91]:
A + B

array([[ 1.7636253 , -0.84593374,  1.091508  ,  2.297664  , -1.1610838 ,
        -0.2936623 , -1.6620547 , -0.25695288, -0.72204256, -0.70522314,
         1.1689937 , -1.895871  , -0.19808222, -1.7825396 , -0.28364456,
        -1.9981496 ],
       [ 0.15033269,  0.3244804 , -1.8895328 , -0.9502002 ,  1.6647085 ,
        -0.8259932 ,  0.1373303 , -1.8100618 , -0.4308654 ,  0.7730532 ,
         0.4350232 , -0.86211747,  1.5323946 , -2.2437816 , -0.7534917 ,
         2.4405954 ],
       [ 0.26749465, -1.6804104 ,  0.6144227 , -1.7138445 , -0.38050115,
        -1.110068  , -0.97117054, -0.49604836,  1.6380664 ,  0.4786678 ,
         0.6972138 ,  0.32852516, -2.307517  , -1.2800252 ,  0.28665483,
         1.6674925 ],
       [ 0.3227167 , -1.6457129 ,  1.601749  , -0.9766537 , -0.12982464,
         0.4094836 ,  0.8133184 ,  2.030057  , -0.01380122,  0.50429726,
         1.6367422 ,  0.99654895,  0.20277873, -0.49592572, -0.78216857,
        -1.3263496 ],
       [ 0.90952176,  1.9513971 , -0

In [95]:
A @ B

array([[ 2.01100135e+00, -3.49316329e-01,  2.92026615e+00,
        -4.17115402e+00,  6.32559657e-01,  3.84469295e+00,
         3.16445780e+00,  3.83602834e+00,  3.68828917e+00,
        -2.22582865e+00,  3.26501966e+00, -2.09240508e+00,
        -1.15379013e-01,  5.41058540e-01, -8.09029484e+00,
        -3.88812470e+00],
       [-4.04904842e+00,  4.06622362e+00, -5.47725630e+00,
        -1.48389542e+00, -2.00363517e+00, -1.73301351e+00,
         9.86627266e-02,  3.72450042e+00, -3.45834470e+00,
        -2.98246598e+00, -8.02406597e+00, -1.75157964e+00,
         1.71081796e-01,  6.31302476e-01,  2.46183729e+00,
         1.83476162e+00],
       [-1.60173357e+00,  1.90065718e+00, -2.51943159e+00,
         6.39216959e-01,  3.42349529e+00,  3.65858197e+00,
        -2.16931701e-01,  4.78230524e+00, -1.20966625e+00,
        -2.82925630e+00,  1.52493393e+00,  3.46248722e+00,
        -7.98471928e+00,  3.13537574e+00, -2.35997796e+00,
        -3.10309029e+00],
       [ 1.91884041e+00,  6.38398170e

In [96]:
R = np.dot(A,B)
R

array([[ 2.01100135e+00, -3.49316329e-01,  2.92026615e+00,
        -4.17115402e+00,  6.32559657e-01,  3.84469295e+00,
         3.16445780e+00,  3.83602834e+00,  3.68828917e+00,
        -2.22582865e+00,  3.26501966e+00, -2.09240508e+00,
        -1.15379013e-01,  5.41058540e-01, -8.09029484e+00,
        -3.88812470e+00],
       [-4.04904842e+00,  4.06622362e+00, -5.47725630e+00,
        -1.48389542e+00, -2.00363517e+00, -1.73301351e+00,
         9.86627266e-02,  3.72450042e+00, -3.45834470e+00,
        -2.98246598e+00, -8.02406597e+00, -1.75157964e+00,
         1.71081796e-01,  6.31302476e-01,  2.46183729e+00,
         1.83476162e+00],
       [-1.60173357e+00,  1.90065718e+00, -2.51943159e+00,
         6.39216959e-01,  3.42349529e+00,  3.65858197e+00,
        -2.16931701e-01,  4.78230524e+00, -1.20966625e+00,
        -2.82925630e+00,  1.52493393e+00,  3.46248722e+00,
        -7.98471928e+00,  3.13537574e+00, -2.35997796e+00,
        -3.10309029e+00],
       [ 1.91884041e+00,  6.38398170e

In [97]:
N

8

In [107]:
A.size

64

In [108]:
A.shape

(8, 8)

In [109]:
B.size

64

In [110]:
B.shape

(8, 8)

In [111]:
T02 = [[1,2],
       [3,4]]
T03 = [[4,3],
       [2,1]]


In [115]:
t1 = np.array(T02)
t2 = np.array(T03)


In [117]:
t1 + t2


array([[5, 5],
       [5, 5]])

In [119]:
tt1 = np.transpose(t1)
tt1

array([[1, 3],
       [2, 4]])

In [120]:
tt2 = np.transpose(t2)
tt2

array([[4, 2],
       [3, 1]])

In [121]:
tt1+tt2

array([[5, 5],
       [5, 5]])

In [122]:
t1 @ t2

array([[ 8,  5],
       [20, 13]])

In [123]:
np.dot(t1,t2)

array([[ 8,  5],
       [20, 13]])

In [126]:
arr01 = [[1,2,3],
         [3,4,5]]
arr02 = [[4,5,6],
         [3,2,1]]
arr01

[[1, 2, 3], [3, 4, 5]]

In [ ]:
arr02


In [127]:
np.cross(arr01, arr02)

array([[-3,  6, -3],
       [-6, 12, -6]])

In [130]:
A.ndim

2

In [131]:
arr03 = np.array([1,2,3])
arr03.ndim

1

In [137]:
d = [[1,2,3,4,5],
     [6,7,8,9,0]]
dnp = np.array(d)
dnp

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [138]:
dnp.T

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 0]])

In [139]:
np.transpose(dnp)

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 0]])

In [141]:
Z = np.random.uniform(-1,1,(N,N))
Z

array([[ 0.81653177, -0.52087622, -0.71021026, -0.02109448,  0.97130091,
        -0.51588946,  0.34427109,  0.52323923],
       [-0.52472491,  0.4564327 , -0.26443373,  0.26461166,  0.26705942,
         0.07154937, -0.81942046,  0.67060499],
       [-0.35843987, -0.62696298, -0.91844972,  0.18178589,  0.35512872,
        -0.96682434,  0.02418612, -0.54700845],
       [ 0.29034558, -0.65126714,  0.38187548, -0.22652931,  0.87345998,
        -0.72495811, -0.3178673 , -0.77305296],
       [ 0.84938724,  0.75467871, -0.48411674,  0.31996809,  0.6344444 ,
         0.11040162,  0.05930116, -0.51629542],
       [-0.81379446,  0.79443152,  0.80083611,  0.26620291, -0.32194042,
        -0.30158085,  0.45191136,  0.79422052],
       [ 0.77417285,  0.55975109,  0.28406329, -0.83172007, -0.67674257,
         0.79710838,  0.21285812, -0.9816059 ],
       [-0.79705691,  0.32700354, -0.98987683, -0.6783839 ,  0.09746758,
         0.3837904 ,  0.30392252, -0.55146138]])